Month 8/step 2
ChrisGomzina/stellar-burgers pull request #3
Opened 2023-01-24 19:42 UTC by ChrisGomzina

2023-01-24 20:12 UTC, andryxxa93 requested changes
Очень хороший проект! `Redux` и `Dnd` настроены и работают корректно.
Что понравилось:
- Правильная структура папок и файлов
- Реализован скролл по категориям
- Код не содержит ничего лишнего

Но есть две проблемы которые необходимо исправить:
- Необходимо приводить к дефолтному состоянию список ингредиентов если произошла ошибка в запросе.
- Необходимо поменять `let` на `const` там где нет переопределения. 

Удачных правок!

2023-01-24 20:12 UTC, andryxxa93 commented on src/components/App/App.jsx
> +  const ingredientsRequest = useSelector((state) => state.ingredientReducer.ingredientsRequest);
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-01-24 20:12 UTC, andryxxa93 commented on src/services/reducers/ingredients.js
> +        ...state,
**Необходимо исправить**
При ошибке запроса необходимо приводить состояние к дефолтному - в том смысле, что список ингредиентов необходимо делать пустым массивом - чтобы пользователь не имел возможности взаимодействовать со старыми данными.

2023-01-24 20:12 UTC, andryxxa93 commented on src/components/Ingredient/Ingredient.jsx
> +  let ingredientsCounter = 0;
**Необходимо исправить**
Используете `let` там где можно `const`.

2023-01-24 20:12 UTC, andryxxa93 commented on src/components/Ingredient/Ingredient.jsx
> +  [addedBun].forEach((bun) => bun._id === id ? (ingredientsCounter += 2) : ingredientsCounter);
**Можно лучше**
Сейчас операции подсчета счетчика будут выполнять каждый рендер. Это можно ограничить с помощью `useEffect` или `useMemo`.

2023-01-24 21:09 UTC, ChrisGomzina commented on src/components/Ingredient/Ingredient.jsx
> +  let ingredientsCounter = 0;
> **Необходимо исправить** Используете `let` там где можно `const`.

Если исправить let на const, то консоль выдает ошибку "Uncaught TypeError: Assignment to constant variable."

2023-01-26 10:18 UTC, andryxxa93 approved these changes
Супер, работа принята, удачного продолжения обучения.

2023-01-26 10:18 UTC, andryxxa93 commented on src/components/Ingredient/Ingredient.jsx
> +  let ingredientsCounter = 0;
да, прошу прощения - проглядел

2023-01-28 14:33 UTC, merged